# Generated by Django 5.2.11 on 2026-02-21 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[('EQUITY', 'Equity'), ('COMMODITY', 'Commodity'), ('BOND', 'Bond'), ('DEPOSIT', 'Deposit'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invested_amount_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_amount_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('profit_loss_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='investments_user_id_45eed0_idx'), models.Index(fields=['investment_type'], name='investments_investm_5110a6_idx'), models.Index(fields=['is_active'], name='investments_is_acti_0a7e01_idx')],
            },
        ),
    ]
