# Generated by Django 5.2.11 on 2026-04-11 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(choices=[('invested', 'Invested Amount'), ('current', 'Current Amount')], max_length=10)),
                ('old_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='investments.investment')),
            ],
            options={
                'db_table': 'investment_logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['investment'], name='investment__investm_a220ef_idx'), models.Index(fields=['changed_at'], name='investment__changed_9d4091_idx')],
            },
        ),
    ]
