# Generated by Django 5.2.11 on 2026-02-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Groceries', 'Groceries'), ('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=50)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Wallet', 'Wallet')], default='Cash', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('EMI', 'EMI'), ('RECURRING', 'Recurring'), ('BILL', 'Bill')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
