# Generated by Django 5.2.11 on 2026-02-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Groceries', 'Groceries'), ('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=50),
        ),
    ]
