# Generated by Django 5.2.11 on 2026-02-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_recurringexpense_expense_recurring_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='billreminder',
            name='expense_created',
            field=models.BooleanField(default=False),
        ),
    ]
