# Generated by Django 5.2.11 on 2026-02-21 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_billreminder_expense_created'),
        ('liabilities', '0003_liabilitypayment_expense_alter_liability_emi_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='liability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='liabilities.liability'),
        ),
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('EMI', 'EMI'), ('RECURRING', 'Recurring'), ('BILL', 'Bill')], default='MANUAL', max_length=20),
        ),
    ]
