# Generated by Django 5.2.11 on 2026-02-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_reminders', '0001_initial'),
    ]

    operations = [
    ]
