# Generated by Django 5.2.11 on 2026-03-03 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_reminders', '0002_initial'),
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billreminder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billreminder',
            name='related_credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_reminders', to='credit_cards.creditcard'),
        ),
    ]
