# Generated by Django 5.2.11 on 2026-03-21 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_reminders', '0003_billreminder_notes_billreminder_related_credit_card'),
        ('credit_cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='billreminder',
            old_name='title',
            new_name='bill_name',
        ),
        migrations.RemoveField(
            model_name='billreminder',
            name='reminder_type',
        ),
        migrations.AddField(
            model_name='billreminder',
            name='category',
            field=models.CharField(choices=[('Electricity', 'Electricity'), ('Water', 'Water'), ('Internet', 'Internet'), ('Mobile', 'Mobile'), ('Insurance', 'Insurance'), ('Rent', 'Rent'), ('Subscriptions', 'Subscriptions'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='billreminder',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billreminder',
            name='parent_reminder',
            field=models.ForeignKey(blank=True, help_text='Reference to the original recurring reminder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_reminders', to='bill_reminders.billreminder'),
        ),
        migrations.AddField(
            model_name='billreminder',
            name='recurring_until_date',
            field=models.DateField(blank=True, help_text='Stop creating reminders after this date (for temporary recurring bills)', null=True),
        ),
        migrations.AlterField(
            model_name='billreminder',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'One Time'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual')], default='ONCE', help_text='How often this bill repeats', max_length=20),
        ),
        migrations.AddIndex(
            model_name='billreminder',
            index=models.Index(fields=['user', 'is_paid'], name='bill_remind_user_id_b400d2_idx'),
        ),
        migrations.AddIndex(
            model_name='billreminder',
            index=models.Index(fields=['user', 'due_date'], name='bill_remind_user_id_59e0a0_idx'),
        ),
    ]
