# Generated by Django 5.2.11 on 2026-03-03 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('card_network', models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('RuPay', 'RuPay'), ('Amex', 'American Express'), ('Other', 'Other')], default='Visa', max_length=20)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_date', models.PositiveIntegerField()),
                ('due_date_days', models.PositiveIntegerField(default=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=36.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
