# Generated by Django 5.2.11 on 2026-02-20 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('liability_type', models.CharField(choices=[('HOME_LOAN', 'Home Loan'), ('CAR_LOAN', 'Car Loan'), ('EDUCATION_LOAN', 'Education Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('CREDIT_CARD', 'Credit Card'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate in percentage', max_digits=5)),
                ('tenure_months', models.IntegerField()),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(db_index=True)),
                ('remaining_months', models.IntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'liabilities',
                'indexes': [models.Index(fields=['user', 'is_active'], name='liabilities_user_id_0f3fc1_idx'), models.Index(fields=['user', 'end_date'], name='liabilities_user_id_93753a_idx')],
            },
        ),
    ]
