# Generated by Django 5.2.11 on 2026-02-21 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('liability_type', models.CharField(choices=[('HOME_LOAN', 'Home Loan'), ('CAR_LOAN', 'Car Loan'), ('EDUCATION_LOAN', 'Education Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('CREDIT_CARD', 'Credit Card'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate in percentage', max_digits=5)),
                ('tenure_months', models.IntegerField()),
                ('start_date', models.DateField()),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remaining_principal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remaining_months', models.IntegerField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'liabilities',
            },
        ),
        migrations.CreateModel(
            name='LiabilityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(db_index=True)),
                ('principal_component', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liability_payments', to='expenses.expense')),
                ('liability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='liabilities.liability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liability_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'liability_payments',
            },
        ),
        migrations.AddIndex(
            model_name='liability',
            index=models.Index(fields=['user', 'is_active'], name='liabilities_user_id_0f3fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='liability',
            index=models.Index(fields=['user', 'end_date'], name='liabilities_user_id_93753a_idx'),
        ),
        migrations.AddIndex(
            model_name='liabilitypayment',
            index=models.Index(fields=['user', 'payment_date'], name='liability_p_user_id_4b2f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='liabilitypayment',
            index=models.Index(fields=['liability', 'payment_date'], name='liability_p_liabili_1caaba_idx'),
        ),
    ]
