# Generated by Django 5.2.11 on 2026-02-20 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiabilityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(db_index=True)),
                ('principal_component', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='liabilities.liability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liability_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'liability_payments',
                'indexes': [models.Index(fields=['user', 'payment_date'], name='liability_p_user_id_4b2f6b_idx'), models.Index(fields=['liability', 'payment_date'], name='liability_p_liabili_1caaba_idx')],
            },
        ),
    ]
